train: [] # metrics that are calculated during training
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.ArgmaxCERMetric
    name: "CER_(Argmax)"
  - _target_: src.metrics.ArgmaxWERMetric
    name: "WER_(Argmax)"
  - _target_: src.metrics.BeamSearchCERMetric
    name: "CER_(LM-BeamSearch)"
    type: "lm"
    beam_size: 5
  - _target_: src.metrics.BeamSearchWERMetric
    name: "WER_(LM-BeamSearch)"
    type: "lm"
    beam_size: 5
